# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Git pull
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@2.9.1

      - name: Login to Ali personal docker registry
        uses: docker/login-action@2.2.0
        with:
          registry: ${{ secrets.ALI_PERSONAL_DOCKER_REGISTIGY_URL }}
          username: ${{ secrets.ALI_PERSONAL_DOCKER_REGISTIGY_USERNAME }}
          password: ${{ secrets.ALI_PERSONAL_DOCKER_REGISTIGY_PASSWORD }}
          logout: false
      # Runs a set of commands using the runners shell
      - name: Use Skopeo Tools Sync Image to Docker Hub
        run: |
          echo Add other actions to build ${{ secrets.ALI_PERSONAL_DOCKER_REGISTIGY_URL }},
          echo test, and deploy your project.
          skopeo copy docker://docker.io/kong/httpbin:0.2.3 docker://${{ secrets.ALI_PERSONAL_DOCKER_REGISTIGY_URL }}/dev/httpbin：0.2.3
